### ISSUE TITLE
Website does not load on FireFox

### ISSUE THREAD

**Issue by AndrewRosenthal** [PECE-project/pece-distro#122] opened 2020-12-18 21:59 UTC
Using FireFox on my computer I get an unable to connect error, requiring me to use Chrome to load the website

**Comment by revagomes** [comment] 2020-12-29 14:27
@AndrewRosenthal 

What is the URL you are having that issue?
What is the version of your Firefox browser?

**Comment by revagomes** [comment] 2021-01-19 01:58
@AndrewRosenthal 

Along with the previous questions, would be great if you could give more detail on the workflow you had  when experienced that issue. It will help me debug it from there. 

Currently I'm not able to reproduce that error even though I'm already using Firefox as my default browser and working with it daily on other PECE sites.

**Comment by akenner** [comment] 2021-01-19 23:06
@revagomes this issue is no longer occurring for @AndrewRosenthal.  I think we can close this one!

**Closed** 2021-02-26 17:06 UTC
