### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by BrianaLeone** [PECE-project/pece-distro#116] opened 2020-11-20 17:25 UTC
I try to upload pdf artifacts but I get the following image
![Screen Shot 2020-11-18 at 11 59 37 AM](https://user-images.githubusercontent.com/72934949/99830307-8501ae00-2b2b-11eb-9e63-1409c87917d8.png)

**Comment by akenner** [comment] 2020-12-04 16:47
This is another one where we believe the user was having internet connection problems, rather than a problem with PECE itself. I recommend closing this issue since we haven't been able to reproduce it.

**Closed** 2020-12-04 18:53 UTC

**Comment by akenner** [comment] 2020-12-07 14:37
OK, so I was wrong. I think this is a valid issue. I just got it myself while creating a PDF artifact. On the third try I was able to create the artifact, but I received the same error that Briana received plus the one below. 

![Screen Shot 2020-12-07 at 9 32 19 AM](https://user-images.githubusercontent.com/1063084/101363790-cb674480-386f-11eb-880e-ea419cce1f22.png)

**Comment by revagomes** [comment] 2021-02-26 17:06
@akenner, 

I've just tried to create a new PDF artifact using my administrator account and it worked well.
Could you please confirm to me if you're still having any issue when uploading files to your PECE instance?

**Comment by akenner** [comment] 2021-02-26 21:47
We are no longer having this issue @revagomes. Thanks!
